const LOGIN_USER = 'LOGIN_USER'
const LOGOUT_USER = 'LOGOUT_USER'
const EDIT_PROFILE = 'EDIT_PROFILE'
const ADD_TO_FAV = 'ADD_TO_FAV'

const GET_ALL_BARS = 'GET_ALL_BARS'
const GET_ALL_BREWS = 'GET_ALL_BREWS'

const ADD_NEW_REQUEST = 'ADD_NEW_REQUEST'
const GET_ALL_REQUESTS = 'GET_ALL_REQUESTS'
const DELETE_REQUEST = 'DELETE_REQUEST'
const EDIT_REQUEST = 'EDIT_REQUEST'

const ADD_NEW_BEER = 'ADD_NEW_BEER'
const GET_ALL_BEERS = 'GET_ALL_BEERS'
const DELETE_BEER = 'DELETE_BEER'
const EDIT_BEER = 'EDIT_BEER'



export { 
  LOGIN_USER, 
  LOGOUT_USER,
  ADD_TO_FAV,
  GET_ALL_BARS, 
  GET_ALL_BREWS, 
  EDIT_PROFILE, 
  ADD_NEW_REQUEST ,
  GET_ALL_REQUESTS,
  DELETE_REQUEST,
  EDIT_REQUEST,
  ADD_NEW_BEER,
  GET_ALL_BEERS,
  DELETE_BEER,
  EDIT_BEER
};
