const LOGIN_USER = 'LOGIN_USER'
const LOGOUT_USER = 'LOGOUT_USER'
const GET_ALL_BARS = 'GET_ALL_BARS'
const GET_ALL_BREWS = 'GET_ALL_BREWS'
const EDIT_PROFILE = 'EDIT_PROFILE'



export { LOGIN_USER, LOGOUT_USER, GET_ALL_BARS, GET_ALL_BREWS, EDIT_PROFILE };
